[4693] Change the FreeMarker import structure
rivetlogic/craftercms-bp-artshowcase pull request #51
Opened 2021-05-28 23:00 UTC by jvega190

https://github.com/craftercms/craftercms/issues/4693

2021-06-04 06:33 UTC, rart approved these changes

2021-06-24 06:06 UTC, rart requested changes
As mentioned on other PRs, use crafter.div instead of tag. Only use tag for items not covered by the element macros. Please update **all** PRs.

2021-06-24 18:14 UTC, rart approved these changes

2021-07-15 10:07 UTC, rart commented on templates/web/page.ftl
>  <#include "/templates/web/navigation/navigation.ftl">
What is navigation still here for?

2021-07-15 15:11 UTC, jvega190 commented on templates/web/page.ftl
>  <#include "/templates/web/navigation/navigation.ftl">
It's not being used, removing

2021-08-12 20:38 UTC, merged